In [2]:
import numpy as np
from numpy.linalg import inv

In [3]:
# module 2 week 2
F = np.array([[1, 0.5], [0, 1]])
P = np.array([[0.01, 0], [0, 1]])
Q = np.array([[0.1, 0], [0, 0.1]])

Pk = F.dot(P).dot(F.T) + Q
Pk

array([[0.36, 0.5 ],
       [0.5 , 1.1 ]])

In [4]:
P1 = Pk
H1 = np.array([[1, 0]])
R1 = np.array([[0.05]])
K1 = P1.dot(H1.T).dot(inv(H1.dot(P1).dot(H1.T) + R1))
K1

array([[0.87804878],
       [1.2195122 ]])

In [5]:
X1_lh = np.array([[2.5], [4]])
Y1 = np.array([[2.2]])
X1_uh = X1_lh + K1.dot(Y1 - H1.dot(X1_lh))
X1_uh

array([[2.23658537],
       [3.63414634]])

In [6]:
P1_uh = (np.eye(2) - K1.dot(H1)).dot(P1)
P1_uh

array([[0.04390244, 0.06097561],
       [0.06097561, 0.4902439 ]])

In [7]:
20/((40-np.pi/6)**2 + 20**2)

0.010212489984000466

In [8]:
# ekf
p1 = np.array([[0.36, 0.5], [0.5, 1.1]])
h1 = np.array([[0.011, 0]])
r1 = np.array([[0.01]])
k1 = p1.dot(h1.T).dot(inv(h1.dot(p1).dot(h1.T) + r1))
k1

array([[0.39428251],
       [0.54761459]])

In [9]:
np.arctan(20/40)

0.4636476090008061

In [10]:
np.pi/6

0.5235987755982988

In [11]:
x1_lh = np.array([[2.5], [4]])
x1_uh = x1_lh + k1 * (np.pi/6 - 0.49)
x1_uh

array([[2.51324741],
       [4.01839918]])

In [12]:
p1_uh = (np.eye(2) - k1.dot(h1)).dot(p1)
p1_uh

array([[0.35843864, 0.49783145],
       [0.49783145, 1.09698812]])

In [13]:
# cholesecky decomposition
A = np.array([[0.01, 0], [0, 1]])
L = np.linalg.cholesky(A)
L

array([[0.1, 0. ],
       [0. , 1. ]])

In [14]:
X_00 = np.array([[0], [5]])
X_01 = X_00 + np.sqrt(3) * np.array([[0.1], [0]])
X_01

array([[0.17320508],
       [5.        ]])

In [15]:
# cholesecky decomposition
A = np.array([[0.36, 0.5], [0.5, 1.1]])
L = np.linalg.cholesky(A)
L

array([[0.6       , 0.        ],
       [0.83333333, 0.63683244]])

In [2]:
import numpy as np

In [9]:
o = np.array([[-0.5],
              [1.5],
              [9],
              [1]])

t = np.array([[1],
            [2],
            [10]])

K = np.array([[640, 0, 640],
               [0, 480, 480],
                [0, 0, 1]])

In [10]:
R = np.array([[1, 0, 0],
              [0, np.cos(np.pi), -np.sin(np.pi)],
              [0, np.sin(np.pi), np.cos(np.pi)]])

In [11]:
Rt = np.hstack((R, t))
Rt

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00],
       [ 0.0000000e+00, -1.0000000e+00, -1.2246468e-16,  2.0000000e+00],
       [ 0.0000000e+00,  1.2246468e-16, -1.0000000e+00,  1.0000000e+01]])

In [15]:
Ocam = K.dot(Rt).dot(o)

In [16]:
Ocam

array([[960.],
       [720.],
       [  1.]])

In [17]:
Opix = Ocam / Ocam[2]

In [18]:
Opix

array([[960.],
       [720.],
       [  1.]])